# Generated by Django 2.2.8 on 2020-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='')),
                ('author', models.CharField(choices=[('lnxpy', 'Ali Reza Yahyapour'), ('hamedsdz', 'Hamed Sadeghzadeh')], max_length=20)),
                ('publish', models.DateField(auto_now=True)),
            ],
        ),
    ]
