# Generated by Django 2.2.8 on 2020-01-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200112_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_avatar'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='city',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
