# Generated by Django 2.2.8 on 2020-01-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_adminprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='email',
        ),
    ]
