# Generated by Django 2.2.8 on 2020-01-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_adminprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
