# Generated by Django 2.2.8 on 2020-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200112_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
