# Generated by Django 2.2.8 on 2020-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200127_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='profile_cover'),
        ),
    ]
