# Generated by Django 2.2.8 on 2020-01-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_adminprofile_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
