# Generated by Django 2.2.8 on 2020-02-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200206_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='', max_length=100),
        ),
    ]
