# Generated by Django 2.2.8 on 2020-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='', max_length=200),
        ),
    ]
